# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 11:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('speaks', '0002_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_id',
            field=models.TextField(default="pre-import", max_length=200, verbose_name='Twitter ID as String'),
            preserve_default=False,
        ),
    ]
